---
- name: Write /etc/network/interfaces.d/can0
  template: src=../templates/can0
            dest=/etc/network/interfaces.d/can0
            owner=root
            group=root
            mode=0644
  register: result

- name: Bring down can0 (ensures changes like bitrate are picked up)
  shell: ifdown --ignore-errors can0
  when: result.changed
  changed_when: result.changed

- name: Bring up can0
  shell: ifup --ignore-errors can0
  changed_when: false

- name: Ensure can0 is up
  shell: ip link show can0 | grep ',UP,'
  changed_when: false
